# Generated by Django 3.0.4 on 2020-03-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_entryform_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryform',
            name='choice',
        ),
        migrations.AddField(
            model_name='entryform',
            name='field_2',
            field=models.CharField(default='green', max_length=200),
        ),
        migrations.AddField(
            model_name='entryform',
            name='field_3',
            field=models.CharField(default='green', max_length=200),
        ),
    ]
