# Generated by Django 3.0.4 on 2020-03-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20200331_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryform',
            name='field_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='field_3',
            field=models.CharField(max_length=200),
        ),
    ]
