# Generated by Django 3.0.4 on 2020-04-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20200331_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='field_4',
            field=models.CharField(default='200', max_length=200),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='field_3',
            field=models.CharField(default='200', max_length=200),
        ),
    ]
