# Generated by Django 3.0.4 on 2020-04-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20200405_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryform',
            name='field_5',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='field_3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entryform',
            name='field_4',
            field=models.CharField(max_length=200),
        ),
    ]
