# Generated by Django 3.0.4 on 2020-04-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_entryform_field_6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryform',
            old_name='field_1',
            new_name='vspherf',
        ),
    ]
