# Generated by Django 3.0.4 on 2020-04-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20200405_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryform',
            name='field_6',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
