# Generated by Django 3.0.4 on 2020-04-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20200405_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryform',
            old_name='field_2',
            new_name='TRAFFICGEN',
        ),
        migrations.RenameField(
            model_name='entryform',
            old_name='field_5',
            new_name='TRAFFICGEN_DURATION',
        ),
        migrations.RenameField(
            model_name='entryform',
            old_name='field_3',
            new_name='TRAFFICGEN_TREX_HOST_IP_ADDR',
        ),
        migrations.RenameField(
            model_name='entryform',
            old_name='field_4',
            new_name='VSWITCH_BRIDGE_NAME',
        ),
        migrations.RenameField(
            model_name='entryform',
            old_name='vspherf',
            new_name='WHITELIST_NICS',
        ),
        migrations.RemoveField(
            model_name='entryform',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='entryform',
            name='field_6',
        ),
        migrations.AddField(
            model_name='entryform',
            name='TRAFFICGEN_LOSSRATE',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='entryform',
            name='TRAFFICGEN_PKT_SIZES',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='entryform',
            name='TRAFFICGEN_RFC2544_TESTS',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='entryform',
            name='TRAFFICGEN_TREX_BASE_DIR',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='entryform',
            name='TRAFFICGEN_TREX_LATENCY_PPS',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='entryform',
            name='TRAFFICGEN_TREX_LINE_SPEED_GBPS',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='entryform',
            name='TRAFFICGEN_TREX_PORT1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='entryform',
            name='TRAFFICGEN_TREX_PORT2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='entryform',
            name='TRAFFICGEN_TREX_PROMISCUOUS',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='entryform',
            name='TRAFFICGEN_TREX_RFC2544_BINARY_SEARCH_LOSS_VERIFICATION',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='entryform',
            name='TRAFFICGEN_TREX_RFC2544_MAX_REPEAT',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='entryform',
            name='TRAFFICGEN_TREX_USER',
            field=models.CharField(default='', max_length=200),
        ),
    ]
